[build]
  command = "echo 'No build step required'"
  publish = "."

[functions]
  node_bundler = "nft"
  included_files = ["views/**", "data/**", "public/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
